### ISSUE TITLE
hi, I faced the following error, while I was running the algorithm on two gpus. tensorflow=1.9.0, using docker container.

### ISSUE THREAD

**Issue by AbidHussain70** [YixuanLi/densenet-tensorflow#22]
[0507 11:40:09 @training.py:50] [DataParallel] Training a model of 2 towers.
[0507 11:40:09 @interface.py:31] Automatically applying QueueInput on the DataFlow.
[0507 11:40:09 @interface.py:43] Automatically applying StagingInput on the DataFlow.
Traceback (most recent call last):
 
    launch_train_with_config(config, SyncMultiGPUTrainer(nr_tower))
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/interface.py", line 90, in launch_train_with_config
    model.get_input_signature(), input,
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/utils/argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/model_desc.py", line 86, in get_input_signature
    inputs = self.inputs()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/model_desc.py", line 116, in inputs
    raise NotImplementedError()
NotImplementedError

**Comment by ppwwyyxx** [comment]
You need https://github.com/YixuanLi/densenet-tensorflow/pull/23
