### ISSUE TITLE
JFYI, win7 64bit Anaconda python 3.5.3 tensorpack 0.3.0 running error 

### ISSUE THREAD

**Issue by iamuspace** [YixuanLi/densenet-tensorflow#7]
Dear. 

Windows 7 64bit 
Anaconda 
python 3.5.3 
tensorpack 0.3.0 

Can I know to fix the error ? 

running error : 

c:\densenet-tensorflow>python cifar10-densenet.py

[32m[0810 18:05:20 @logger.py:107][0m Use a new log directory train_log/cifar1
0-single-fisrt150-second225-max3000810-180520
[32m[0810 18:05:20 @logger.py:73][0m Argv: cifar10-densenet.py
[32m[0810 18:05:20 @fs.py:89][0m [5m[31mWRN[0m Env var $TENSORPACK_DATASET
not set, using C:\Users\java\tensorpack_data for datasets.
[32m[0810 18:05:20 @cifar.py:33][0m Found cifar10 data in C:\Users\java\tensor
pack_data\cifar10_data.

Traceback (most recent call last):
  File "cifar10-densenet.py", line 174, in <module>
    config = get_config()
  File "cifar10-densenet.py", line 143, in get_config
    dataset_train = get_data('train')
  File "cifar10-densenet.py", line 135, in get_data
    ds = PrefetchData(ds, 3, 2)
  File "c:\anaconda3\lib\site-packages\tensorpack\dataflow\prefetch.py", line 84
, in __init__
    start_proc_mask_signal(self.procs)
  File "c:\anaconda3\lib\site-packages\tensorpack\utils\concurrency.py", line 21
2, in start_proc_mask_signal
    p.start()
  File "c:\anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\anaconda3\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "c:\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 66, in __in
it__
    reduction.dump(process_obj, to_child)
  File "c:\anaconda3\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'MapDataComponent.__init__.<locals>.f'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "c:\anaconda3\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input

**Comment by ppwwyyxx** [comment]
Looks like `PrefetchData` doesn't support windows very well.
You can try removing `ds = PrefetchData(ds, 3, 2)` to see if it works (slower).
